---
- name: "[main] Include variables for {{ vim_plugin_manager }} plugin manager"
  include_vars: "{{ vim_plugin_manager }}.yml"
  tags: vim

- name: "[main] Import cleanup tasks"
  import_tasks: cleanup.yml
  when: vim_cleanup
  tags:
  - vim
  - vim_cleanup

- name: "[main] Import dependencies installation tasks"
  import_tasks: dependencies.yml
  tags:
  - vim
  - vim_dependencies

- name: "[main] Include Darwin-specific tasks if provisioning MacOS"
  include_tasks: darwin.yml
  when: "'Darwin' in ansible_os_family"
  tags: vim

- name: "[main] Include vim installation tasks"
  include_tasks: non-darwin.yml
  when: "not 'Darwin' in ansible_os_family"
  tags: vim

- name: "[main] Include vars for {{ vim_env }}-wide installation"
  include_vars: "{{ vim_env }}.yml"
  tags: vim

- name: "[main] Include system configuration tasks"
  include_tasks: system.yml
  when:
  - "'system' in vim_env"
  - "not 'Darwin' in ansible_os_family"
  tags: vim

- name: "[main] Include user configuration tasks"
  include_tasks: users.yml
  when: "'user' in vim_env or 'Darwin' in ansible_os_family"
  tags: vim

- name: "[main] Include vim-airline configuration if installing airline"
  include_tasks: airline.yml
  with_items: "{{ vim_plugins }}"
  when: item.name == 'vim-airline/vim-airline'
  tags: vim

- name: "[main] Include neovim installation tasks"
  include_tasks: nvim.yml
  when: vim_neovim
  tags: vim
